/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejerciciosboletinex1.adivinaElnumero;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class jframeAdivinaElnumero extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(jframeAdivinaElnumero.class.getName());

    /**
     * Creates new form jframeAdivinaElnumero
     */
    public jframeAdivinaElnumero() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText(org.openide.util.NbBundle.getMessage(jframeAdivinaElnumero.class, "jframeAdivinaElnumero.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // 1. Generar número aleatorio 1-10
        int numeroAleatorio = (int) (Math.random() * 10) + 1;

        boolean acertado = false;

        do {
            String respuesta = JOptionPane.showInputDialog(this, "Adivina el número (1-10):");

            if (respuesta != null) { // Si no pulsa Cancelar
                try {
                    int numeroUsuario = Integer.parseInt(respuesta);

                    if (numeroUsuario == numeroAleatorio) {
                        JOptionPane.showMessageDialog(this, "¡Acertaste! Era el " + numeroAleatorio);
                        acertado = true;
                    } else {

                        if (numeroUsuario > numeroAleatorio) {

                            JOptionPane.showMessageDialog(this, "Intenta de nuevo. El número es menor   " + numeroAleatorio);

                        } else if (numeroUsuario < numeroAleatorio) {

                            JOptionPane.showMessageDialog(this, "Intenta de nuevo. El número es mayor   " + numeroAleatorio);

                        }

                    }
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Debes ingresar un número válido");
                }
            } else {
                // Si pulsa Cancelar, salir del bucle
                break;
            }
        } while (!acertado);

     }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new jframeAdivinaElnumero().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables

}
