/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejerciciosboletinex1.ejercicio2;

import org.netbeans.validation.api.builtin.stringvalidation.StringValidators;
import org.netbeans.validation.api.ui.ValidationGroup;

/**
 *
 * @author Usuario
 */
public class JframeMascota extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JframeMascota.class.getName());

    /**
     * Creates new form JframeMascota
     */
    public JframeMascota() {
        initComponents();
        
        
        ValidationGroup group = validationPanel1.getValidationGroup();
        group.add(campotextoNombre, StringValidators.REQUIRE_NON_EMPTY_STRING);
                group.add(campotextoNombre, StringValidators.HOST_NAME);

        group.add(campotextoEdad, StringValidators.REQUIRE_VALID_INTEGER);
        
        
        
  // Aquí puedes modificar los textos directamente
    
        imagen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlabelTipo = new javax.swing.JLabel();
        campotextoNombre = new javax.swing.JTextField();
        TipoAnimal = new javax.swing.JComboBox<>();
        jlabelNombre = new javax.swing.JLabel();
        campotextoEdad = new javax.swing.JTextField();
        jlabelEdad = new javax.swing.JLabel();
        ETIQUETAIMAGENES = new javax.swing.JLabel();
        validationPanel1 = new org.netbeans.validation.api.ui.swing.ValidationPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlabelTipo.setText(org.openide.util.NbBundle.getMessage(JframeMascota.class, "JframeMascota.jlabelTipo.text")); // NOI18N

        campotextoNombre.setText(org.openide.util.NbBundle.getMessage(JframeMascota.class, "JframeMascota.campo texto.text")); // NOI18N
        campotextoNombre.setName("campo texto"); // NOI18N
        campotextoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campotextoNombreActionPerformed(evt);
            }
        });

        TipoAnimal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gato", "Perro", "Paloma", "otro" }));
        TipoAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoAnimalActionPerformed(evt);
            }
        });

        jlabelNombre.setText(org.openide.util.NbBundle.getMessage(JframeMascota.class, "JframeMascota.jlabelNombre.text")); // NOI18N
        jlabelNombre.setToolTipText(org.openide.util.NbBundle.getMessage(JframeMascota.class, "JframeMascota.jlabelNombre.toolTipText")); // NOI18N

        campotextoEdad.setName("campo nombre"); // NOI18N
        campotextoEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campotextoEdadActionPerformed(evt);
            }
        });

        jlabelEdad.setText(org.openide.util.NbBundle.getMessage(JframeMascota.class, "JframeMascota.jlabelEdad.text")); // NOI18N

        ETIQUETAIMAGENES.setText(org.openide.util.NbBundle.getMessage(JframeMascota.class, "JframeMascota.ETIQUETAIMAGENES.text")); // NOI18N
        ETIQUETAIMAGENES.setToolTipText(org.openide.util.NbBundle.getMessage(JframeMascota.class, "JframeMascota.ETIQUETAIMAGENES.toolTipText")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(ETIQUETAIMAGENES, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlabelEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campotextoEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlabelTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TipoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campotextoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(41, 41, 41)
                        .addComponent(validationPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campotextoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TipoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlabelTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campotextoEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlabelEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(validationPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ETIQUETAIMAGENES, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void TipoAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoAnimalActionPerformed

        String seleccion = (String) TipoAnimal.getSelectedItem(); // Obtener el animal seleccionado
        String ruta = "/ejerciciosboletinex1/ejercicio2/imagenes/"; // Carpeta de imágenes
        javax.swing.ImageIcon icono = null;

 
    switch (seleccion) {
        case "Gato":
            icono = new javax.swing.ImageIcon(getClass().getResource("/iconsimageexample/interfaz/imgs/imagenGato.jpg"));
            break;
        case "Perro":
            icono = new javax.swing.ImageIcon(getClass().getResource("/iconsimageexample/interfaz/imgs/imagenPerro.jpg"));
            break;
        case "Paloma":
            icono = new javax.swing.ImageIcon(getClass().getResource("/iconsimageexample/interfaz/imgs/imagenPaloma.jpg"));
            break;
        case "otro":
            icono = new javax.swing.ImageIcon(getClass().getResource("/iconsimageexample/interfaz/imgs/tiporaro.jpg"));
            break;
    }
 // Escalar la imagen al tamaño del JLabel
    if (icono != null) {
        java.awt.Image imgEscalada = icono.getImage().getScaledInstance(
            ETIQUETAIMAGENES.getWidth(),
            ETIQUETAIMAGENES.getHeight(),
            java.awt.Image.SCALE_SMOOTH
        );
        ETIQUETAIMAGENES.setIcon(new javax.swing.ImageIcon(imgEscalada));
        ETIQUETAIMAGENES.setText(""); // Quita el texto si lo hubiera
    } else {
        ETIQUETAIMAGENES.setIcon(null);
        ETIQUETAIMAGENES.setText("Imagen no encontrada");
    }
    }//GEN-LAST:event_TipoAnimalActionPerformed


    private void campotextoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campotextoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campotextoNombreActionPerformed

    private void campotextoEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campotextoEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campotextoEdadActionPerformed

    public void imagen() {

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JframeMascota().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ETIQUETAIMAGENES;
    private javax.swing.JComboBox<String> TipoAnimal;
    private javax.swing.JTextField campotextoEdad;
    private javax.swing.JTextField campotextoNombre;
    private javax.swing.JLabel jlabelEdad;
    private javax.swing.JLabel jlabelNombre;
    private javax.swing.JLabel jlabelTipo;
    private org.netbeans.validation.api.ui.swing.ValidationPanel validationPanel1;
    // End of variables declaration//GEN-END:variables
}
