/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejerciciosboletinex1.ejercicio6;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Usuario
 */
public class jframeTablaPuntajes extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(jframeTablaPuntajes.class.getName());
    private TableRowSorter<TableModel> sorter;

    /**
     * Creates new form jframeTablaPuntajes
     */
   public jframeTablaPuntajes() {
    initComponents();

    DefaultTableModel cambioNombre = new DefaultTableModel();
    String titulo[] = {"jugador", "puntaje", "nivel"};
    cambioNombre.setColumnIdentifiers(titulo);
    jTable1.setModel(cambioNombre);

    sorter = new TableRowSorter<>(cambioNombre);
    jTable1.setRowSorter(sorter);

    // ✅ CONFIGURACIÓN CON LAMBDAS (más compacta)
    sorter.setComparator(1, java.util.Comparator.naturalOrder()); // Puntaje
    sorter.setComparator(2, java.util.Comparator.naturalOrder()); // Nivel

    sorter.setSortKeys(java.util.Arrays.asList(
            new javax.swing.RowSorter.SortKey(1, javax.swing.SortOrder.DESCENDING)
    ));
}

    public void alta(Jugador jugador) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        Object[] fila = {
            jugador.getNombre(),
            jugador.getPuntaje(),
            jugador.getNivel(),};
        model.addRow(fila);
            if (sorter != null) {
        sorter.sort();
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BotonValoresAleatorios = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        BotonValoresAleatorios.setText(org.openide.util.NbBundle.getMessage(jframeTablaPuntajes.class, "jframeTablaPuntajes.BotonValoresAleatorios.text")); // NOI18N
        BotonValoresAleatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonValoresAleatoriosActionPerformed(evt);
            }
        });

        jButton2.setText(org.openide.util.NbBundle.getMessage(jframeTablaPuntajes.class, "jframeTablaPuntajes.jButton2.text")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText(org.openide.util.NbBundle.getMessage(jframeTablaPuntajes.class, "jframeTablaPuntajes.jLabel1.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BotonValoresAleatorios, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47))
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonValoresAleatorios)
                    .addComponent(jButton2))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        añadirJugador dialogoAlta = new añadirJugador(this, true);

        dialogoAlta.setVisible(true);


    }//GEN-LAST:event_jButton2ActionPerformed

    private void BotonValoresAleatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonValoresAleatoriosActionPerformed

        String[] nombres = {"Ana", "Carlos", "Maria", "Luis", "Elena", "Pedro", "Sofia", "Javier", "Laura", "Diego"};

        // Seleccionar un nombre aleatorio
        int indiceNombre = (int) (Math.random() * nombres.length);
        String nombre = nombres[indiceNombre];

        // Generar puntuación y nivel aleatorios
        int puntuacion = (int) (Math.random() * 1000) + 100;
        int nivel = (int) (Math.random() * 10) + 1;

        // Crear y añadir el jugador
        Jugador jugador = new Jugador(nombre, puntuacion, nivel);
        LogicaJugadores.añadirJugador(jugador);
        alta(jugador);


    }//GEN-LAST:event_BotonValoresAleatoriosActionPerformed
    private void refrescarTabla() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // limpia las filas

        for (Jugador jugador : LogicaJugadores.getListaJugadores()) {
            model.addRow(new Object[]{
                jugador.getNombre(),
                jugador.getPuntaje(),
                jugador.getNivel()
            });
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new jframeTablaPuntajes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonValoresAleatorios;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
